# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:title

# Setup
title:               Qoders Blog
tagline:             ""
paginate:            6
paginate_path:       "/blog/page:num/"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Qadeer Ahmad Khan
  url:               https://www.linkedin.com/in/qadeer-ahmad-khan
  email:             ahm.qadeer@gmail.com

# Custom vars
version:             2.0.0
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

plugins:
  - jekyll-paginate
  - jekyll-gist
#  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-seo-tag

